apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: demo-app
  labels:
     app: demo
spec: 
 replicas: 3
selector:
matchLabels: 
 app: demo
template:
  metadata: 
   labels:
     app: demo
 spec: 
  containers: 
  - name: demo-contaier
    image: ghandgevikas/demo:latest
    Ports:
    - containersPort: 3000

------------------------------------------------------------------------------------


     