apiVersion: apps/v1 
kind: deployment 
metadata: 
  name: nginx
  labels: 
   app: nginx 
spec: 
 replicas: 3
 selector: 
  matchLabels: 
   app: nginx
   template: 
    metadata: 
     labels: 
      app:   

  