FROM ubuntu:latest
RUN apt-get update && apt install nginx
COPY /src/.  .
EXPOSE 80
CMD [ "nginx", "daemon", "off";]

FROM #base image
RUN   # it will run commands while continer is creating like install packages 
COPY # it will copy containt from local host machine to docker container 
WORKDIR /the/workdir/path


