apiVersion: v1
kind: pod
metadata: 
  name: my-app
  labels: 
  app: my-app
spec: 
 containers:
   - name: my-conatiner
     image:  nginx:latest
     resources:    
      limits:
        cpu: "500m"
        memory: "125Mi"
     ports:
      - containerPort: 80

---

apiVersion: v1
kind: Service
metadata: 
 name: 
